---
- name:  Configure Organization | Validate Required Parameters
  assert:
    that:
    - "satellite_organization is defined"
    - "satellite_organization['name'] is defined"

- name:  Configure Organization | Create Organization
  foreman_organization:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ satellite_organization['name'] }}"
  delegate_to: "{{ satellite_api_basion }}"
  tags:
  - satellite_organizations

- name:  Configure Organization | Upload Manifest
  katello_manifest:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    manifest_path: "{{ satellite_organization['manifest'] }}"
  delegate_to: "{{ satellite_api_basion }}"
  when: satellite_organization['manifest'] is defined
  tags:
  - satellite_manifests

- name:  Configure Organization | Include Tasks to Create Lifecycle Environment Path
  include_tasks: create-lifecycle-environment-path.yml
  loop: "{{ satellite_organization['lifecycle_environment_paths'] }}"
  loop_control:
    loop_var: lifecycle_environment_path
  when: satellite_organization['lifecycle_environment_paths'] is defined
  tags:
  - satellite_lifecycle_environments

- name: Configure Organization | Enable Red Hat Repository
  katello_repository_set:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    name: "{{ repository['name'] }}"
    product: "{{ repository['product'] }}"
    repositories:
    - releasever: "{{ repository['releasever'] | default() }}"
      basearch: "{{ repository['basearch'] }}"
    state: enabled
  loop: "{{ satellite_organization['repositories'] }}"
  loop_control:
    loop_var: repository
  delegate_to: "{{ satellite_api_basion }}"
  when: satellite_organization['repositories'] is defined
  tags:
  - satellite_repositories

- name: Configure Organization | Create Sync Plans
  katello_sync_plan:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    name: "{{ sync_plan['name'] }}"
    interval: "{{ sync_plan['interval'] }}"
    products: "{{ sync_plan['products'] }}"
    sync_date: "{{ sync_plan['sync_date'] | default(ansible_date_time.date + ' 00:00:00') }}"
    enabled: "{{ sync_plan['enabled'] | default(True) }}"
  loop: "{{ satellite_organization['sync_plans'] }}"
  loop_control:
    loop_var: sync_plan
  delegate_to: "{{ satellite_api_basion }}"
  when: satellite_organization['sync_plans'] is defined
  tags:
  - satellite_sync_plans

- name: Configure Organization | Immediate Sync Products Async
  katello_sync:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    product: "{{ immediate_sync_product }}"
  loop: "{{ satellite_organization['immediate_sync_products'] }}"
  loop_control:
    loop_var: immediate_sync_product
  delegate_to: "{{ satellite_api_basion }}"
  register: immediate_sync_products_results
  async: 3600
  poll: 0
  when: satellite_organization['immediate_sync_products'] is defined
  tags:
  - satellite_immediate_sync

- name: Configure Organizations | Immediate Sync Products Async | Wait for async tasks
  async_status:
    jid: "{{ immediate_sync_products_result.ansible_job_id }}"
  loop: "{{ immediate_sync_products_results.results }}"
  loop_control:
    loop_var: "immediate_sync_products_result"
  delegate_to: localhost
  register: async_immediate_sync_products_results
  until: async_immediate_sync_products_results.finished
  retries: 120
  sleep: 30
  tags:
  - satellite_immediate_sync

- name: Configure Organizations | Create Content Views
  katello_content_view:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    name: "{{ content_view['name'] }}"
    repositories: "{{ content_view['repositories'] }}"
  loop: "{{ satellite_organization['content_views'] }}"
  loop_control:
    loop_var: content_view
  delegate_to: "{{ satellite_api_basion }}"
  when: satellite_organization['content_views'] is defined
  tags:
  - satellite_content_views

- name: Configure Organizations | Create Composite Content Views
  katello_content_view:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    name: "{{ composite_content_view['name'] }}"
    composite: True
    content_views: "{{ composite_content_view['content_views'] }}"
  loop: "{{ satellite_organization['composite_content_views'] }}"
  loop_control:
    loop_var: composite_content_view
  delegate_to: "{{ satellite_api_basion }}"
  when: satellite_organization['composite_content_views'] is defined
  tags:
  - satellite_composite_content_views
