---
- name: Create Lifecycle Environment Path | Validate Required Parameters
  assert:
    that:
    - "satellite_organization is defined"
    - "satellite_organization['name'] is defined"
    - "lifecycle_environment_path is defined"
    - "lifecycle_environment_path['environments'] is defined"
  tags:
  - satellite_lifecycle_environments

- name: Create Lifecycle Environment Path | Create Lifecycle Environment
  katello_lifecycle_environment:
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ satellite_organization['name'] }}"
    name: "{{ lifecycle_environment }}"
    prior: "{{ ((lifecycle_environment_index-1) >= 0) | ternary(lifecycle_environment_path['environments'][lifecycle_environment_index-1], 'Library') }}"
  loop: "{{ lifecycle_environment_path['environments'] }}"
  loop_control:
    index_var: lifecycle_environment_index
    loop_var: lifecycle_environment
  delegate_to: "{{ satellite_api_basion }}"
  tags:
  - satellite_lifecycle_environments
